export const SKILL_OPTIONS = [
    '.NET',
    '.NET Core',
    '3D Modeling',
    'ActiveMQ',
    'Actix',
    'Adobe XD',
    'AdonisJS',
    'After Effects',
    'Agile',
    'Algolia',
    'Alibaba Cloud',
    'Alpine.js',
    'Amazon Aurora',
    'Amazon RDS',
    'Amazon SQS',
    'Amplify',
    'Amplitude',
    'Android',
    'Angular',
    'Ansible',
    'Ant',
    'Ant Design',
    'Apache',
    'Apache Airflow',
    'Apache Beam',
    'Apache Flink',
    'Apache Hadoop',
    'Apache Kafka',
    'Apache Lucene',
    'Apache Solr',
    'Apache Spark',
    'Apache Superset',
    'API Gateway',
    'Apigee',
    'AppDynamics',
    'Application Insights',
    'Appium',
    'ArangoDB',
    'Architecture',
    'Arduino',
    'ArgoCD',
    'ARM',
    'Artillery',
    'ASP.NET',
    'ASP.NET Core',
    'Assembly',
    'Astro',
    'Asana',
    'Axum',
    'Axure',
    'Azure',
    'Azure AD',
    'Azure App Service',
    'Azure DevOps',
    'Azure Functions',
    'Azure Kubernetes',
    'Azure Logic Apps',
    'Azure Monitor',
    'Azure Repos',
    'Azure Service Bus',
    'Azure SQL',
    'Azure Storage',
    'Azure VMs',
    'Babel',
    'Backbone.js',
    'Balsamiq',
    'Bamboo',
    'Bash',
    'Bazel',
    'BDD',
    'Beego',
    'BEM',
    'BERT',
    'BGP',
    'BigCommerce',
    'BigQuery',
    'Bitcoin',
    'Bitbucket',
    'Blazor',
    'Blender',
    'Blockchain',
    'Bootstrap',
    'Bottle',
    'Browserify',
    'Buck',
    'Buffalo',
    'Bugsnag',
    'Bulma',
    'Bundler',
    'C',
    'C#',
    'C++',
    'CakePHP',
    'Capybara',
    'Cardano',
    'Cassandra',
    'CAUTION',
    'CDN',
    'Celery',
    'Chai',
    'Chakra UI',
    'CherryPy',
    'CircleCI',
    'ClickUp',
    'Clojure',
    'Cloud Functions',
    'Cloud Pub/Sub',
    'Cloud Run',
    'Cloud Spanner',
    'Cloud Storage',
    'CloudFormation',
    'CloudFront',
    'CloudWatch',
    'CMake',
    'CNN',
    'CoAP',
    'COBOL',
    'CockroachDB',
    'Code Review',
    'CodeIgniter',
    'Communication',
    'Composer',
    'Compute Engine',
    'Computer Vision',
    'Conda',
    'Confluence',
    'Consul',
    'Containerd',
    'Contentful',
    'Cordova',
    'Cosmos DB',
    'CouchDB',
    'Couchbase',
    'CQRS',
    'CSS Modules',
    'CSS3',
    'Cucumber',
    'Cypress',
    'Dart',
    'Data Analysis',
    'Data Pipeline',
    'Data Science',
    'Data Warehousing',
    'Datadog',
    'Databricks',
    'dbt',
    'Deep Learning',
    'DeFi',
    'DigitalOcean',
    'DirectX',
    'Django',
    'DNS',
    'Docker',
    'Docker Compose',
    'Docker Swarm',
    'Domain-Driven Design',
    'Drone CI',
    'Dropwizard',
    'Drupal',
    'Dynatrace',
    'DynamoDB',
    'E-commerce',
    'EC2',
    'Echo',
    'ECS',
    'EKS',
    'Elastic Beanstalk',
    'Elasticsearch',
    'Elixir',
    'ELK Stack',
    'Embedded C',
    'Embedded Systems',
    'Ember.js',
    'Emotion',
    'Encryption',
    'Entity Framework',
    'Envoy',
    'Erlang',
    'ES6+',
    'ESBuild',
    'etcd',
    'Ethereum',
    'ETL',
    'Event Sourcing',
    'Event-Driven Architecture',
    'Excel',
    'F#',
    'Falcon',
    'FastAPI',
    'Fastify',
    'Fiber',
    'Figma',
    'Firebase',
    'Firebase Firestore',
    'Firestore',
    'Firewall',
    'Flask',
    'Flux',
    'Fortran',
    'Foundation',
    'Framer',
    'FreeRTOS',
    'GameMaker',
    'Gatling',
    'Gatsby',
    'GCP',
    'Ghost',
    'Gin',
    'Git',
    'GitHub',
    'GitHub Actions',
    'GitLab',
    'GitLab CI',
    'GKE',
    'Go',
    'Godot',
    'Golang',
    'Google Analytics',
    'Google Cloud Platform',
    'Google Cloud SQL',
    'Google Data Studio',
    'Google Pub/Sub',
    'GPT',
    'Gradle',
    'Grafana',
    'GraphQL',
    'Groovy',
    'gRPC',
    'Grunt',
    'Gulp',
    'Hanami',
    'HAProxy',
    'Hardhat',
    'Harness',
    'Haskell',
    'Headless CMS',
    'Helm',
    'Heroku',
    'Hibernate',
    'HLSL',
    'HTTP/HTTPS',
    'Hugging Face',
    'Hyperledger',
    'IBM Cloud',
    'InfluxDB',
    'Insomnia',
    'Interaction Design',
    'InVision',
    'Ionic',
    'IoT',
    'Istio',
    'Jasmine',
    'Java',
    'JavaScript',
    'JMeter',
    'Jest',
    'Jetpack Compose',
    'Jira',
    'JPA',
    'Joomla',
    'JSF',
    'Julia',
    'JUnit',
    'Jupyter',
    'Jupyter Notebook',
    'JWT',
    'k6',
    'Kafka',
    'Kanban',
    'Karma',
    'Keras',
    'Keycloak',
    'Kibana',
    'Koa',
    'Kong',
    'Kotlin',
    'Kubernetes',
    'Lambda',
    'LangChain',
    'Laravel',
    'LDAP',
    'Leadership',
    'Lean',
    'Less',
    'LightGBM',
    'Linear',
    'Linode',
    'Linkerd',
    'Lit',
    'Load Balancing',
    'LoadRunner',
    'Locust',
    'Logstash',
    'Looker',
    'LoopBack',
    'LoRaWAN',
    'LSTM',
    'Lua',
    'Machine Learning',
    'Magento',
    'Make',
    'MariaDB',
    'Material-UI',
    'MATLAB',
    'MAUI',
    'Maven',
    'Maya',
    'Meilisearch',
    'Mentoring',
    'Mercurial',
    'MetaMask',
    'Metabase',
    'Meteor',
    'Micronaut',
    'Microcontrollers',
    'Microservices',
    'Mixpanel',
    'Mocha',
    'Mockito',
    'Monday.com',
    'MongoDB',
    'Monolith',
    'MPLS',
    'MQTT',
    'MS SQL Server',
    'NATS',
    'NativeScript',
    'Neo4j',
    'NestJS',
    'Netlify',
    'Network Security',
    'Neural Networks',
    'New Relic',
    'Next.js',
    'NFT',
    'NGINX',
    'NLP',
    'Node.js',
    'Nomad',
    'Notion',
    'npm',
    'NuGet',
    'NumPy',
    'NUnit',
    'Nuxt.js',
    'OAuth',
    'Objective-C',
    'OCaml',
    'Okta',
    'OpenAI',
    'OpenAPI',
    'OpenCart',
    'OpenCV',
    'OpenGL',
    'OpenShift',
    'Oracle',
    'Oracle Cloud',
    'OSPF',
    'Other',
    'OWASP',
    'Padrino',
    'PagerDuty',
    'Pandas',
    'Pants',
    'Parcel',
    'penetration Testing',
    'Perforce',
    'Perl',
    'Phalcon',
    'Phaser',
    'PhoneGap',
    'Photoshop',
    'PHP',
    'PHPUnit',
    'pip',
    'Play Framework',
    'Playwright',
    'pnpm',
    'Podman',
    'Poetry',
    'Polygon',
    'PostgreSQL',
    'PostCSS',
    'Postman',
    'Power BI',
    'PowerShell',
    'Preact',
    'PrestaShop',
    'Prisma',
    'Problem Solving',
    'Prometheus',
    'Prototyping',
    'Pulumi',
    'Puppeteer',
    'Pyramid',
    'PyTest',
    'Python',
    'PyTorch',
    'Qlik',
    'Quarkus',
    'Qwik',
    'R',
    'RabbitMQ',
    'Railway',
    'Rancher',
    'Raspberry Pi',
    'RavenDB',
    'RDS',
    'React',
    'React Native',
    'Redis',
    'Redis Pub/Sub',
    'Redshift',
    'Remix',
    'Render',
    'REST API',
    'Revel',
    'RNN',
    'Rocket',
    'Rollbar',
    'Rollup',
    'Route 53',
    'RSpec',
    'Ruby',
    'Ruby on Rails',
    'RubyGems',
    'Rust',
    'S3',
    'SAFe',
    'Sails.js',
    'SAML',
    'Sanity',
    'Sass',
    'Scala',
    'Scikit-learn',
    'SciPy',
    'SCSS',
    'Scrum',
    'Seaborn',
    'Security Auditing',
    'Segment',
    'Selenium',
    'Semantic UI',
    'Sensors',
    'Sentry',
    'Sequelize',
    'Shader Programming',
    'Shell Scripting',
    'Shopify',
    'Sidekiq',
    'SignalR',
    'Sinatra',
    'Sketch',
    'Slim',
    'Smart Contracts',
    'Snowflake',
    'SNS',
    'SOA',
    'SOAP',
    'Socket.io',
    'Solana',
    'Solidity',
    'SolidJS',
    'spaCy',
    'Spinnaker',
    'Splunk',
    'Spring Boot',
    'Spring Framework',
    'Spring MVC',
    'Sprint Planning',
    'SQL',
    'SQLAlchemy',
    'SQLite',
    'SQS',
    'SSL/TLS',
    'Statistics',
    'Stencil',
    'Strapi',
    'Struts',
    'Styled Components',
    'Stylus',
    'Svelte',
    'SVN',
    'SWC',
    'Swagger',
    'Swift',
    'SwiftUI',
    'Symfony',
    'System Design',
    'Tableau',
    'Tailwind CSS',
    'TCP/IP',
    'TDD',
    'TeamCity',
    'Technical Documentation',
    'Tekton',
    'TensorFlow',
    'Terraform',
    'TestCafe',
    'Testing Library',
    'TestNG',
    'Three.js',
    'TimescaleDB',
    'Tokio',
    'Tornado',
    'Traefik',
    'Transformers',
    'Travis CI',
    'Trello',
    'Truffle',
    'Turbopack',
    'Tyk',
    'TypeORM',
    'TypeScript',
    'Typesense',
    'UI/UX Design',
    'UIKit',
    'Unity',
    'Unreal Engine',
    'User Research',
    'Vercel',
    'Vite',
    'VPN',
    'Vue',
    'Vulnerability Assessment',
    'Vulkan',
    'Vultr',
    'Warp',
    'Waterfall',
    'Web3',
    'WebDriver',
    'WebGL',
    'Webpack',
    'WebRTC',
    'WebSockets',
    'WinForms',
    'Wireframing',
    'WooCommerce',
    'WordPress',
    'WPF',
    'Xamarin',
    'XGBoost',
    'Xcode',
    'xUnit',
    'Yarn',
    'Yii',
    'Zend',
    'Zephyr',
    'Zeplin',
    'Zigbee',
];
